audio_vae:
  tod_vae_ckpt: /data/weiminwang//kaggle/tmp/mm_audio_/kaggle/tmp/v1-16.pth
  bigvgan_vocoder_ckpt: /data/weiminwang//kaggle/tmp/mm_audio_/kaggle/tmp/best_netG.pt
  mode: 16k
  need_vae_encoder: True 